// <auto-generated />
using System;
using ClinicManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicManager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicManager.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("nhanVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BenhNhan", b =>
                {
                    b.Property<int>("benhNhanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("benhNhanId"));

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nguoiGioiThieuId")
                        .HasColumnType("int");

                    b.Property<string>("soDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("benhNhanId");

                    b.ToTable("BenhNhans");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BenhNhanGoiDieuTri", b =>
                {
                    b.Property<int>("benhNhanGoiDieuTriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("benhNhanGoiDieuTriId"));

                    b.Property<int>("benhNhanId")
                        .HasColumnType("int");

                    b.Property<int>("goiDieuTriId")
                        .HasColumnType("int");

                    b.Property<int>("khamBenhId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayMua")
                        .HasColumnType("datetime2");

                    b.Property<int>("soBuoiDaDung")
                        .HasColumnType("int");

                    b.Property<int>("tongSoBuoi")
                        .HasColumnType("int");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("benhNhanGoiDieuTriId");

                    b.ToTable("BenhNhanGoiDieuTris");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BuoiDieuTri", b =>
                {
                    b.Property<int>("buoiDieuTriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("buoiDieuTriId"));

                    b.Property<int>("benhNhanGoiDieuTriId")
                        .HasColumnType("int");

                    b.Property<int>("benhNhanId")
                        .HasColumnType("int");

                    b.Property<string>("chiDinhDacBiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("gioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("gioKetThuc")
                        .HasColumnType("time");

                    b.Property<DateTime>("ngayDieuTri")
                        .HasColumnType("datetime2");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("buoiDieuTriId");

                    b.ToTable("BuoiDieuTris");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BuoiDieuTriNhanVien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("buoiDieuTriId")
                        .HasColumnType("int");

                    b.Property<int>("nhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("vaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("BuoiDieuTriNhanViens");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.ChamCong", b =>
                {
                    b.Property<int>("chamCongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chamCongId"));

                    b.Property<bool>("anTrua")
                        .HasColumnType("bit");

                    b.Property<bool>("nghiPhep")
                        .HasColumnType("bit");

                    b.Property<bool>("nghiPhepCoLuong")
                        .HasColumnType("bit");

                    b.Property<int>("nhanVienId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("thoiGianRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoiGianVao")
                        .HasColumnType("datetime2");

                    b.HasKey("chamCongId");

                    b.ToTable("ChamCongs");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.ChamCongAudit", b =>
                {
                    b.Property<int>("chamCongAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chamCongAuditId"));

                    b.Property<int>("adminNhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("chamCongId")
                        .HasColumnType("int");

                    b.Property<string>("lyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("nghiPhepCoLuongCu")
                        .HasColumnType("bit");

                    b.Property<bool>("nghiPhepCoLuongMoi")
                        .HasColumnType("bit");

                    b.Property<bool>("nghiPhepCu")
                        .HasColumnType("bit");

                    b.Property<bool>("nghiPhepMoi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("suaLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("thoiGianRaCu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("thoiGianRaMoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("thoiGianVaoCu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("thoiGianVaoMoi")
                        .HasColumnType("datetime2");

                    b.HasKey("chamCongAuditId");

                    b.ToTable("ChamCongAudits");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.DatLichKham", b =>
                {
                    b.Property<int>("datLichKhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("datLichKhamId"));

                    b.Property<int?>("bacSiDuKienId")
                        .HasColumnType("int");

                    b.Property<int?>("benhNhanId")
                        .HasColumnType("int");

                    b.Property<string>("ghiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoiGianHen")
                        .HasColumnType("datetime2");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("datLichKhamId");

                    b.ToTable("DatLichKhams");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.GoiDieuTri", b =>
                {
                    b.Property<int>("goiDieuTriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("goiDieuTriId"));

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("hoatDong")
                        .HasColumnType("bit");

                    b.Property<bool>("macDinh")
                        .HasColumnType("bit");

                    b.Property<string>("tenGoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tongSoBuoi")
                        .HasColumnType("int");

                    b.HasKey("goiDieuTriId");

                    b.ToTable("GoiDieuTris");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.KhamBenh", b =>
                {
                    b.Property<int>("khamBenhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("khamBenhId"));

                    b.Property<int>("bacSiId")
                        .HasColumnType("int");

                    b.Property<int>("benhNhanId")
                        .HasColumnType("int");

                    b.Property<string>("chanDoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("goiDieuTriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayKham")
                        .HasColumnType("datetime2");

                    b.Property<string>("phacDoDieuTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("tinhTrangThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("khamBenhId");

                    b.ToTable("KhamBenhs");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.NhanVien", b =>
                {
                    b.Property<int>("nhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nhanVienId"));

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hoatDong")
                        .HasColumnType("bit");

                    b.Property<decimal>("luongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("vaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nhanVienId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.ThuocVatTuBuoiDieuTri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("buoiDieuTriId")
                        .HasColumnType("int");

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<int>("vatTuId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ThuocVatTuBuoiDieuTris");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.VatTu", b =>
                {
                    b.Property<int>("vatTuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vatTuId"));

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("donViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenVatTu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tonKho")
                        .HasColumnType("int");

                    b.HasKey("vatTuId");

                    b.ToTable("VatTus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
