// <auto-generated />
using System;
using ClinicManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicManager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicManager.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("nhanVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BangLuongThang", b =>
                {
                    b.Property<int>("bangLuongThangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bangLuongThangId"));

                    b.Property<bool>("daChot")
                        .HasColumnType("bit");

                    b.Property<int>("nam")
                        .HasColumnType("int");

                    b.Property<int>("nhanVienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("thang")
                        .HasColumnType("int");

                    b.Property<decimal>("tongLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("bangLuongThangId");

                    b.ToTable("BangLuongThangs");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BangLuongThangChiTiet", b =>
                {
                    b.Property<int>("bangLuongThangChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bangLuongThangChiTietId"));

                    b.Property<int>("bangLuongThangId")
                        .HasColumnType("int");

                    b.Property<string>("dienGiai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("loai")
                        .HasColumnType("int");

                    b.Property<decimal>("soTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("bangLuongThangChiTietId");

                    b.HasIndex("bangLuongThangId");

                    b.ToTable("BangLuongThangChiTiets");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BenhNhan", b =>
                {
                    b.Property<int>("benhNhanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("benhNhanId"));

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nguoiGioiThieuId")
                        .HasColumnType("int");

                    b.Property<string>("soDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("benhNhanId");

                    b.ToTable("BenhNhans");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BenhNhanGoiDieuTri", b =>
                {
                    b.Property<int>("benhNhanGoiDieuTriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("benhNhanGoiDieuTriId"));

                    b.Property<int>("benhNhanId")
                        .HasColumnType("int");

                    b.Property<int>("goiDieuTriId")
                        .HasColumnType("int");

                    b.Property<int>("khamBenhId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayMua")
                        .HasColumnType("datetime2");

                    b.Property<int>("soBuoiDaDung")
                        .HasColumnType("int");

                    b.Property<int>("tongSoBuoi")
                        .HasColumnType("int");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("benhNhanGoiDieuTriId");

                    b.ToTable("BenhNhanGoiDieuTris");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BuoiDieuTri", b =>
                {
                    b.Property<int>("buoiDieuTriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("buoiDieuTriId"));

                    b.Property<int?>("bacSiDieuTriTayId")
                        .HasColumnType("int");

                    b.Property<int>("benhNhanId")
                        .HasColumnType("int");

                    b.Property<string>("chiDinhDacBiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("chiPhiThuocVatTu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("dotDieuTriId")
                        .HasColumnType("int");

                    b.Property<int?>("kyThuatVienTapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayDieuTri")
                        .HasColumnType("datetime2");

                    b.Property<string>("noiDungDieuTriTay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noiDungTap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("buoiDieuTriId");

                    b.HasIndex("bacSiDieuTriTayId");

                    b.HasIndex("dotDieuTriId");

                    b.HasIndex("kyThuatVienTapId");

                    b.ToTable("BuoiDieuTris");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BuoiDieuTriAudit", b =>
                {
                    b.Property<int>("buoiDieuTriAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("buoiDieuTriAuditId"));

                    b.Property<int>("adminNhanVienId")
                        .HasColumnType("int");

                    b.Property<int?>("bacSiDieuTriTayIdCu")
                        .HasColumnType("int");

                    b.Property<int?>("bacSiDieuTriTayIdMoi")
                        .HasColumnType("int");

                    b.Property<int>("buoiDieuTriId")
                        .HasColumnType("int");

                    b.Property<string>("chiDinhDacBietCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chiDinhDacBietMoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("chiPhiThuocVatTuCu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("chiPhiThuocVatTuMoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("kyThuatVienTapIdCu")
                        .HasColumnType("int");

                    b.Property<int?>("kyThuatVienTapIdMoi")
                        .HasColumnType("int");

                    b.Property<string>("lyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngayDieuTriCu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayDieuTriMoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("noiDungDieuTriTayCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noiDungDieuTriTayMoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noiDungTapCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noiDungTapMoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("suaLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("buoiDieuTriAuditId");

                    b.ToTable("BuoiDieuTriAudits");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BuoiDieuTriNhanVien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("buoiDieuTriId")
                        .HasColumnType("int");

                    b.Property<int>("nhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("vaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("BuoiDieuTriNhanViens");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.CauHinhLuong", b =>
                {
                    b.Property<int>("cauHinhLuongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cauHinhLuongId"));

                    b.Property<DateTime>("apDungTuNgay")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("gioBatDauChieu")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("gioBatDauSang")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("gioKetThucChieu")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("gioKetThucSang")
                        .HasColumnType("time");

                    b.Property<decimal>("heSoTangCaNgayLe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("heSoTangCaNgayThuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("phanTramGioiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("soGioLamChuanNgay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("soPhutLamTronTangCa")
                        .HasColumnType("int");

                    b.Property<int>("soPhutToiThieuTinhTangCa")
                        .HasColumnType("int");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("tienAnTruaNgay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tienChuyenCan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tienDieuTriTayMoiBuoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tienTapMoiBuoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tienXangXeThang")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("cauHinhLuongId");

                    b.ToTable("CauHinhLuongs");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.ChamCong", b =>
                {
                    b.Property<int>("chamCongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chamCongId"));

                    b.Property<bool>("anTrua")
                        .HasColumnType("bit");

                    b.Property<bool>("nghiPhep")
                        .HasColumnType("bit");

                    b.Property<bool>("nghiPhepCoLuong")
                        .HasColumnType("bit");

                    b.Property<int>("nhanVienId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("thoiGianRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoiGianVao")
                        .HasColumnType("datetime2");

                    b.HasKey("chamCongId");

                    b.ToTable("ChamCongs");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.ChamCongAudit", b =>
                {
                    b.Property<int>("chamCongAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chamCongAuditId"));

                    b.Property<int>("adminNhanVienId")
                        .HasColumnType("int");

                    b.Property<int>("chamCongId")
                        .HasColumnType("int");

                    b.Property<string>("lyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("nghiPhepCoLuongCu")
                        .HasColumnType("bit");

                    b.Property<bool>("nghiPhepCoLuongMoi")
                        .HasColumnType("bit");

                    b.Property<bool>("nghiPhepCu")
                        .HasColumnType("bit");

                    b.Property<bool>("nghiPhepMoi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("suaLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("thoiGianRaCu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("thoiGianRaMoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("thoiGianVaoCu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("thoiGianVaoMoi")
                        .HasColumnType("datetime2");

                    b.HasKey("chamCongAuditId");

                    b.ToTable("ChamCongAudits");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.DatLichKham", b =>
                {
                    b.Property<int>("datLichKhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("datLichKhamId"));

                    b.Property<int?>("bacSiDuKienId")
                        .HasColumnType("int");

                    b.Property<int?>("benhNhanId")
                        .HasColumnType("int");

                    b.Property<string>("ghiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("thoiGianHen")
                        .HasColumnType("datetime2");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("datLichKhamId");

                    b.ToTable("DatLichKhams");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.DotDieuTri", b =>
                {
                    b.Property<int>("dotDieuTriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dotDieuTriId"));

                    b.Property<int>("bacSiKhamId")
                        .HasColumnType("int");

                    b.Property<int>("benhNhanId")
                        .HasColumnType("int");

                    b.Property<string>("chanDoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("daThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("goiDieuTriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayKham")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("phacDoDieuTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("phanTramGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("soBuoiDaDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("tongSoBuoi")
                        .HasColumnType("int");

                    b.Property<decimal>("tongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("trangThai")
                        .HasColumnType("int");

                    b.HasKey("dotDieuTriId");

                    b.HasIndex("goiDieuTriId");

                    b.ToTable("DotDieuTris");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.DotDieuTriMuaThem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("dotDieuTriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("muaLuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("soBuoiThem")
                        .HasColumnType("int");

                    b.Property<decimal>("soTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("DotDieuTriMuaThems");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.GoiDieuTri", b =>
                {
                    b.Property<int>("goiDieuTriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("goiDieuTriId"));

                    b.Property<decimal>("gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("hoatDong")
                        .HasColumnType("bit");

                    b.Property<int>("soBuoi")
                        .HasColumnType("int");

                    b.Property<string>("tenGoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("goiDieuTriId");

                    b.ToTable("GoiDieuTris");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.KhamBenh", b =>
                {
                    b.Property<int>("khamBenhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("khamBenhId"));

                    b.Property<int>("bacSiId")
                        .HasColumnType("int");

                    b.Property<int>("benhNhanId")
                        .HasColumnType("int");

                    b.Property<string>("chanDoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("goiDieuTriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayKham")
                        .HasColumnType("datetime2");

                    b.Property<string>("phacDoDieuTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("tinhTrangThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("khamBenhId");

                    b.ToTable("KhamBenhs");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.NgayLe", b =>
                {
                    b.Property<int>("ngayLeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ngayLeId"));

                    b.Property<bool>("coTinhLuong")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ngay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ngayLeId");

                    b.ToTable("NgayLes");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.NhanVien", b =>
                {
                    b.Property<int>("nhanVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nhanVienId"));

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hoatDong")
                        .HasColumnType("bit");

                    b.Property<decimal>("luongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("vaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nhanVienId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.PhieuNhapKho", b =>
                {
                    b.Property<int>("phieuNhapKhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("phieuNhapKhoId"));

                    b.Property<string>("duongDanHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("nhanVienNhapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("tongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("phieuNhapKhoId");

                    b.ToTable("PhieuNhapKhos");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.PhieuNhapKhoChiTiet", b =>
                {
                    b.Property<int>("phieuNhapKhoChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("phieuNhapKhoChiTietId"));

                    b.Property<decimal>("donGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("phieuNhapKhoId")
                        .HasColumnType("int");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("thanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("vatTuId")
                        .HasColumnType("int");

                    b.HasKey("phieuNhapKhoChiTietId");

                    b.HasIndex("vatTuId");

                    b.ToTable("PhieuNhapKhoChiTiets");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.ThanhToan", b =>
                {
                    b.Property<int>("thanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("thanhToanId"));

                    b.Property<int?>("buoiDieuTriId")
                        .HasColumnType("int");

                    b.Property<bool>("daChot")
                        .HasColumnType("bit");

                    b.Property<int?>("dotDieuTriId")
                        .HasColumnType("int");

                    b.Property<string>("ghiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hinhThuc")
                        .HasColumnType("int");

                    b.Property<int>("loai")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayThu")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("soTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("taoLuc")
                        .HasColumnType("datetime2");

                    b.HasKey("thanhToanId");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.ThuocVatTuBuoiDieuTri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("buoiDieuTriId")
                        .HasColumnType("int");

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<int>("vatTuId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("buoiDieuTriId");

                    b.HasIndex("vatTuId");

                    b.ToTable("ThuocVatTuBuoiDieuTris");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.VatTu", b =>
                {
                    b.Property<int>("vatTuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vatTuId"));

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("donViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("loai")
                        .HasColumnType("int");

                    b.Property<string>("tenVatTu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tonKho")
                        .HasColumnType("int");

                    b.HasKey("vatTuId");

                    b.ToTable("VatTus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BangLuongThangChiTiet", b =>
                {
                    b.HasOne("ClinicManager.Models.Entities.BangLuongThang", null)
                        .WithMany("ChiTiets")
                        .HasForeignKey("bangLuongThangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BuoiDieuTri", b =>
                {
                    b.HasOne("ClinicManager.Models.Entities.NhanVien", "BacSiDieuTriTay")
                        .WithMany()
                        .HasForeignKey("bacSiDieuTriTayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClinicManager.Models.Entities.DotDieuTri", "DotDieuTri")
                        .WithMany("BuoiDieuTris")
                        .HasForeignKey("dotDieuTriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManager.Models.Entities.NhanVien", "NguoiTap")
                        .WithMany()
                        .HasForeignKey("kyThuatVienTapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BacSiDieuTriTay");

                    b.Navigation("DotDieuTri");

                    b.Navigation("NguoiTap");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.DotDieuTri", b =>
                {
                    b.HasOne("ClinicManager.Models.Entities.GoiDieuTri", "GoiDieuTri")
                        .WithMany()
                        .HasForeignKey("goiDieuTriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoiDieuTri");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.PhieuNhapKhoChiTiet", b =>
                {
                    b.HasOne("ClinicManager.Models.Entities.VatTu", "vatTu")
                        .WithMany()
                        .HasForeignKey("vatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vatTu");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.ThuocVatTuBuoiDieuTri", b =>
                {
                    b.HasOne("ClinicManager.Models.Entities.BuoiDieuTri", "BuoiDieuTri")
                        .WithMany()
                        .HasForeignKey("buoiDieuTriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManager.Models.Entities.VatTu", "VatTu")
                        .WithMany()
                        .HasForeignKey("vatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuoiDieuTri");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicManager.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.BangLuongThang", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("ClinicManager.Models.Entities.DotDieuTri", b =>
                {
                    b.Navigation("BuoiDieuTris");
                });
#pragma warning restore 612, 618
        }
    }
}
